version: '3.4'

networks:
  drivingSchoolNetworks:

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12345

  drivingschool.api:
    container_name: DrivingSchoolApiContainer
    image: ${DOCKER_REGISTRY-}drivingschoolapi
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: DrivingSchool.API/Dockerfile
    depends_on: 
      - SqlServerDb

  drivingschool.frontend:
    container_name: DrivingSchoolFrontendContainer
    image: drivingschoolfrontend
    ports:
      - 3000:3000
    build:
      context: ../../frontend/drivingschool/
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline